# Generated by Django 5.2.8 on 2025-11-17 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_aiquizrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AIQuizRequest',
        ),
    ]
