# Generated by Django 5.2.8 on 2025-11-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_delete_aiquizrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
       	migrations.AddField(
       	model_name='quiz',
   	 name='slug',
   	 field=models.SlugField(max_length=255, unique=False, null=True, blank=True),
	),
        migrations.AddField(
            model_name='quiz',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
