# Generated by Django 5.2.8 on 2025-11-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_question_difficulty_question_explanation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='time_limit_minutes',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
