# Generated by Django 5.2.8 on 2025-11-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_remove_quiz_tags_remove_quiz_time_limit_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
